name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - run: npm ci
      - run: npm test
